name: TownyChat
main: com.palmergames.bukkit.TownyChat.Chat
version: 0.35
author: ElgarL, Shade, phrstbrn
website: http://code.google.com/a/eclipselabs.org/p/towny/
description: >
    TownyChat plugin which hooks Towny.

softdepend: [Towny, CraftIRC]

############################################################
# +------------------------------------------------------+ #
# |                 TownyChat commands                   | #
# +------------------------------------------------------+ #
############################################################
commands:
    townychat:
        aliases: []
        usage: /townychat reload
        permission: townychat.reload
    channel:
        aliases: [ch]
        description: Channel leaving and joining
        usage: /<command> leave|join channel
    leave:
        description: Leaves a channel
        usage: /<command> channel
    join:
        description: Joins a channel
        usage: /<command> channel
    chmute:
        aliases: [mute]
        description: Mutes a player in a channel
        usage: /<command> channel player
        permission: townychat.mod.mute
    mutelist:
        description: Displays mute list for a channel
        usage: /<command> channel
    chunmute:
        aliases: [unmute]
        description: Unmutes a player in a channel
        usage: /<command> channel player
        permission: townychat.mod.unmute
            
############################################################
# +------------------------------------------------------+ #
# |                     Permissions                      | #
# +------------------------------------------------------+ #
############################################################
permissions:
    townychat.reload:
        description: Allows reloading of Townychat.
        default: op
