name: TownyChat
main: com.palmergames.bukkit.TownyChat.Chat
version: 0.31
author: ElgarL, Shade, phrstbrn
website: http://code.google.com/a/eclipselabs.org/p/towny/
description: >
    TownyChat plugin which hooks Towny.

softdepend: [Towny]

############################################################
# +------------------------------------------------------+ #
# |                 TownyChat commands                   | #
# +------------------------------------------------------+ #
############################################################
commands:
    townychat:
        aliases: []
        usage: /townychat reload
        permission: townychat.reload
        
############################################################
# +------------------------------------------------------+ #
# |                     Permissions                      | #
# +------------------------------------------------------+ #
############################################################
permissions:
    townychat.reload:
        description: Allows reloading of Townychat.
        default: op